/* ── public entry & globals ─────────────────────────────────────────────── */

/** The Orion API. Component packages extend it (see the component interfaces above). */
export interface Orion extends OrionCore, OrionComponents {
  [extension: string]: any;
}
/** Component APIs are merged into this interface by the component declaration files. */
export interface OrionComponents {}

declare const Orion: Orion;
export default Orion;
export { Orion };

declare global {
  interface Window {
    Orion: Orion;
    OrionConfig?: OrionConfig;
  }
  /** Component tags are added by types/components/zz-elements.d.ts (generated by build/gen-types.mjs). */
  interface HTMLElementTagNameMap {
    'o-icon': OIconElement;
  }
  interface DocumentEventMap {
    'o-ready': CustomEvent<{ version: string }>;
    'o-theme': CustomEvent<{ mode: ThemeMode; resolved: 'light' | 'dark' }>;
    'o-locale': CustomEvent<{ locale: string }>;
  }
}
